server:
  port: 9001
#  context-path: /cc

page: 1
pageSize: 10

pageInfo:
  index: "${page}"
  size: "${pageSize}"
  total: 100


datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/hui
  username: root
  password: 111111
jpa:
  hibernate:
    ddl-auto: create
  show-sql: trur